add miss constructor
chenshuo/muduo-udns pull request #1
Opened 2016-09-22 17:16 UTC by zhoudayang

2016-09-23 16:15 UTC, chenshuo commented on Resolver.cc
> +
remove this empty line.

2016-09-23 16:16 UTC, chenshuo commented on Resolver.cc
> +    assert(ctx_ !=NULL);
Need a space between '!=' and NULL.

2016-09-23 16:16 UTC, chenshuo commented on Resolver.cc
> +    ::dns_add_serv_s(ctx_,nameServer.getSockAddr());
Need one space after each comma (,), same for next line.

2016-09-23 16:17 UTC, chenshuo requested changes

2016-09-28 05:21 UTC, zhoudayang commented
Thank you! I'm sorry for my carelessness.

2016-09-28 23:59 UTC, merged